set nocompatible
colorscheme industry
syntax on
filetype plugin on
set background=dark
set number
set ruler
set cursorline
set noerrorbells
set mouse=a
set hidden
set noswapfile
set nobackup
set autoread
set guifont=JetBrains\ Mono\ Regular:h10
" Maximize window when opening.
au GUIEnter * simalt ~x
" Issues with backspace on insert mode
set backspace=indent,eol,start
" what in indentation
set tabstop=4 
set softtabstop=4 
set shiftwidth=4
set smartindent
" GUI components
set guioptions-=m " Remove menu bar
set guioptions-=T " Remove toolbar
set guioptions-=r " Remove rh scroll
set guioptions-=L " Remove lh scroll
